import 'package:flutter/material.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedWheredidyougoonvacationwithinthelastyearWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedIntercontinentalWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedComponent4Widget1.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedComponent5Widget.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedInternationalWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/Generated29CleanTravellerWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedNovacationWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedDomesticdifferentregionWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedDomesticownregionWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedBackbuttonWidget2.dart';

/* Frame q2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQ2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.800000011920929,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 385.0,
          height: 800.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 241, 241, 243),
                  ),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 67.0,
                  height: 34.0,
                  child: TransformHelper.translate(
                      x: -124.00,
                      y: -344.00,
                      z: 0,
                      child: GeneratedBackbuttonWidget2()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 50.0,
                  child: TransformHelper.translate(
                      x: -1.00,
                      y: -265.00,
                      z: 0,
                      child: Generated29CleanTravellerWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 59.0,
                  child: TransformHelper.translate(
                      x: -1.00,
                      y: -201.50,
                      z: 0,
                      child:
                          GeneratedWheredidyougoonvacationwithinthelastyearWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -89.50,
                      z: 0,
                      child: GeneratedRectangle7Widget1()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 277.0,
                  height: 35.0,
                  child: TransformHelper.translate(
                      x: 2.00,
                      y: -87.50,
                      z: 0,
                      child: GeneratedNovacationWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -25.50,
                      z: 0,
                      child: GeneratedRectangle8Widget1()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 277.0,
                  height: 35.0,
                  child: TransformHelper.translate(
                      x: 2.00,
                      y: -23.50,
                      z: 0,
                      child: GeneratedDomesticownregionWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 38.50,
                      z: 0,
                      child: GeneratedRectangle9Widget1()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 277.0,
                  height: 35.0,
                  child: TransformHelper.translate(
                      x: 2.00,
                      y: 40.50,
                      z: 0,
                      child: GeneratedDomesticdifferentregionWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 102.50,
                      z: 0,
                      child: GeneratedRectangle10Widget1()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 280.0,
                  height: 38.0,
                  child: TransformHelper.translate(
                      x: 2.50,
                      y: 106.00,
                      z: 0,
                      child: GeneratedInternationalWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 166.50,
                      z: 0,
                      child: GeneratedRectangle11Widget1()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 280.0,
                  height: 38.0,
                  child: TransformHelper.translate(
                      x: 2.50,
                      y: 170.00,
                      z: 0,
                      child: GeneratedIntercontinentalWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 289.50,
                      z: 0,
                      child: GeneratedComponent4Widget1()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 289.50,
                      z: 0,
                      child: GeneratedComponent5Widget()),
                )
              ]),
        ),
      ),
    ));
  }
}
