import 'package:flutter/material.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedWheredidyougoonvacationwithinthelastyearWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedIntercontinentalWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedComponent4Widget1.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedComponent5Widget.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedInternationalWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/Generated29CleanTravellerWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedNovacationWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedDomesticdifferentregionWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedDomesticownregionWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq2widget/generated/GeneratedBackbuttonWidget2.dart';

/* Frame q2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQ2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.800000011920929,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 385.0,
          height: 800.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 241, 241, 243),
                  ),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 67.0,
                  height: 34.0,
                  child: TransformHelper.translate(
                      x: -124.00,
                      y: -295.00,
                      z: 0,
                      child: GeneratedBackbuttonWidget2()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 50.0,
                  child: TransformHelper.translate(
                      x: -1.00,
                      y: -250.00,
                      z: 0,
                      child: Generated29CleanTravellerWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 59.0,
                  child: TransformHelper.translate(
                      x: -1.00,
                      y: -201.50,
                      z: 0,
                      child:
                          GeneratedWheredidyougoonvacationwithinthelastyearWidget()),
                ),

                // No vacation btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -89.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 0;
                        },
                        child: Text('No vacation',
                          style: TextStyle(
                            color: Colors.black,
                            height: 1.171875,
                            fontSize: 18.0,
                            fontFamily: 'Forum',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                        style: ButtonStyle(
                            backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                        ),
                      )),
                ),

                // Domestic, own region btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -25.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 10;
                        },
                        child: Text('Domestic, own region',
                          style: TextStyle(
                            color: Colors.black,
                            height: 1.171875,
                            fontSize: 18.0,
                            fontFamily: 'Forum',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                        style: ButtonStyle(
                          backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                        ),
                      )),
                ),

                // Domestic, different region btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 38.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 30;
                        },
                        child: Text('Domestic, different region',
                          style: TextStyle(
                            color: Colors.black,
                            height: 1.171875,
                            fontSize: 18.0,
                            fontFamily: 'Forum',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                        style: ButtonStyle(
                          backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                        ),
                      )),
                ),

                // International btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 102.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 40;
                        },
                        child: Text('International',
                          style: TextStyle(
                            color: Colors.black,
                            height: 1.171875,
                            fontSize: 18.0,
                            fontFamily: 'Forum',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                        style: ButtonStyle(
                          backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                        ),
                      )),
                ),

                // Intercontinental btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 166.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 70;
                        },
                        child: Text('Intercontinental',
                          style: TextStyle(
                            color: Colors.black,
                            height: 1.171875,
                            fontSize: 18.0,
                            fontFamily: 'Forum',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                        style: ButtonStyle(
                          backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                        ),
                      )),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 289.50,
                      z: 0,
                      child: GeneratedComponent4Widget1()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 289.50,
                      z: 0,
                      child: GeneratedComponent5Widget()),
                )
              ]),
        ),
      ),
    ));
  }
}
