import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/eco_trackapp/generatedaboutpagewidget/generated/GeneratedWelcometoWidget2.dart';
import 'package:flutterapp/eco_trackapp/generatedaboutpagewidget/generated/GeneratedNavigationbarWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedaboutpagewidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu1.dart';
import 'package:flutterapp/eco_trackapp/generatedaboutpagewidget/generated/GeneratedEcoTrackWidget4.dart';
import 'package:flutterapp/eco_trackapp/generatedaboutpagewidget/generated/GeneratedAndroidBrowserFrameWidget.dart';

/* Frame about page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAboutpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.800000011920929,
      child: GestureDetector(
        onTap: () =>
            Navigator.pushNamed(context, '/GeneratedProgresspageWidget'),
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                Container(

                  width: MediaQuery.of(context).size.width ,
                  height: 800.0,
                  child: Stack(
                      fit: StackFit.expand,
                      alignment: Alignment.center,
                      overflow: Overflow.visible,
                      children: [
                        ClipRRect(
                          borderRadius: BorderRadius.zero,
                          child: Container(
                            color: Color.fromARGB(255, 241, 241, 243),
                          ),
                        ),
                        Positioned(
                          left: null,
                          top: null,
                          right: null,
                          bottom: null,
                          width: 246.0,
                          height: 51.0,
                          child: TransformHelper.translate(
                              x: 2.50,
                              y: -256.50,
                              z: 0,
                              child: GeneratedWelcometoWidget2()),
                        ),
                        Positioned(
                          left: null,
                          top: null,
                          right: null,
                          bottom: null,
                          width: 280.0,
                          height: 373.0,
                          child: TransformHelper.translate(
                              x: 1.50,
                              y: 68.50,
                              z: 0,
                              child:
                                  GeneratedLoremipsumdolorsitametconsecteturadipiscingelitseddoeiu1()),
                        ),
                        Positioned(
                          left: null,
                          top: null,
                          right: null,
                          bottom: null,
                          width: 222.0,
                          height: 85.0,
                          child: TransformHelper.translate(
                              x: 0.50,
                              y: -190.50,
                              z: 0,
                              child: GeneratedEcoTrackWidget4()),
                        ),
                        Positioned(
                          left: null,
                          top: null,
                          right: null,
                          bottom: null,
                          width: 324.0,
                          height: 26.0,
                          child: TransformHelper.translate(
                              x: 0.50,
                              y: -371.00,
                              z: 0,
                              child: GeneratedAndroidBrowserFrameWidget()),
                        )
                      ]),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 385.0,
                  height: 54.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 373.00,
                      z: 0,
                      child: GeneratedNavigationbarWidget()),
                )
              ]),
        ),
      ),
    ));
  }
}
