import 'package:flutter/material.dart';
import 'package:flutterapp/eco_trackapp/generatedq7widget/generated/GeneratedAlwaysWidget1.dart';
import 'package:flutterapp/eco_trackapp/generatedq7widget/generated/GeneratedComponent5Widget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/eco_trackapp/generatedq7widget/generated/GeneratedComponent4Widget8.dart';
import 'package:flutterapp/eco_trackapp/generatedq7widget/generated/Generated79WasteConsciousWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq7widget/generated/GeneratedSometimesWidget1.dart';
import 'package:flutterapp/eco_trackapp/generatedq7widget/generated/GeneratedRectangle7Widget8.dart';
import 'package:flutterapp/eco_trackapp/generatedq7widget/generated/GeneratedRectangle10Widget8.dart';
import 'package:flutterapp/eco_trackapp/generatedq7widget/generated/GeneratedRarelyWidget1.dart';
import 'package:flutterapp/eco_trackapp/generatedq7widget/generated/GeneratedRectangle9Widget7.dart';
import 'package:flutterapp/eco_trackapp/generatedq7widget/generated/GeneratedDoesyourhouseholdrecycleWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq7widget/generated/GeneratedNeverWidget1.dart';
import 'package:flutterapp/eco_trackapp/generatedq7widget/generated/GeneratedRectangle8Widget8.dart';
import 'package:flutterapp/eco_trackapp/generatedq7widget/generated/GeneratedBackbuttonWidget9.dart';

/* Frame q7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQ7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.800000011920929,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 385.0,
          height: 800.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 241, 241, 243),
                  ),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 67.0,
                  height: 34.0,
                  child: TransformHelper.translate(
                      x: -124.00,
                      y: -295.00,
                      z: 0,
                      child: GeneratedBackbuttonWidget9()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 50.0,
                  child: TransformHelper.translate(
                      x: -1.00,
                      y: -250.00,
                      z: 0,
                      child: Generated79WasteConsciousWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 59.0,
                  child: TransformHelper.translate(
                      x: -1.00,
                      y: -201.50,
                      z: 0,
                      child: GeneratedDoesyourhouseholdrecycleWidget()),
                ),

                // Always btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -89.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 0;
                        },
                        child: Text('Always',
                            style: TextStyle(
                                color:Colors.black
                            )),
                        style: ButtonStyle(
                            backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                        ),
                      ))
                ),

                // Sometimes btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -25.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 10;
                        },
                        child: Text('Sometimes',
                            style: TextStyle(
                                color:Colors.black
                            )),
                        style: ButtonStyle(
                            backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                        ),
                      ))
                ),


                // Rarely btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 38.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 15;
                        },
                        child: Text('Rarely',
                            style: TextStyle(
                                color:Colors.black
                            )),
                        style: ButtonStyle(
                            backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                        ),
                      ))
                ),


                // Never btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 102.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 20;
                        },
                        child: Text('Never',
                            style: TextStyle(
                                color:Colors.black
                            )),
                        style: ButtonStyle(
                            backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                        ),
                      ))
                ),


                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 289.50,
                      z: 0,
                      child: GeneratedComponent4Widget8()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 289.50,
                      z: 0,
                      child: GeneratedComponent5Widget7()),
                )
              ]),
        ),
      ),
    ));
  }
}
