import 'package:flutter/material.dart';
import 'package:flutterapp/eco_trackapp/generatedq9widget/generated/Generated0Widget.dart';
import 'package:flutterapp/eco_trackapp/generatedq9widget/generated/Generated99WasteConsciousWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq9widget/generated/GeneratedRectangle8Widget7.dart';
import 'package:flutterapp/eco_trackapp/generatedq9widget/generated/GeneratedRectangle9Widget6.dart';
import 'package:flutterapp/eco_trackapp/generatedq9widget/generated/GeneratedComponent5Widget6.dart';
import 'package:flutterapp/eco_trackapp/generatedq9widget/generated/GeneratedRectangle11Widget4.dart';
import 'package:flutterapp/eco_trackapp/generatedq9widget/generated/GeneratedBackbuttonWidget8.dart';
import 'package:flutterapp/eco_trackapp/generatedq9widget/generated/GeneratedRectangle7Widget7.dart';
import 'package:flutterapp/eco_trackapp/generatedq9widget/generated/Generated13Widget.dart';
import 'package:flutterapp/eco_trackapp/generatedq9widget/generated/GeneratedComponent4Widget7.dart';
import 'package:flutterapp/eco_trackapp/generatedq9widget/generated/Generated10Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/eco_trackapp/generatedq9widget/generated/GeneratedRectangle10Widget7.dart';
import 'package:flutterapp/eco_trackapp/generatedq9widget/generated/Generated710Widget.dart';
import 'package:flutterapp/eco_trackapp/generatedq9widget/generated/GeneratedHowmanymealsperweekdoyoueatmeatorfishWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq9widget/generated/Generated46Widget.dart';

/* Frame q9
    Autogenerated by FlutLab FTF Generator
  */

class GeneratedQ9Widget extends StatefulWidget {
  @override
  _GeneratedQ9Widget createState() => _GeneratedQ9Widget();
}
class _GeneratedQ9Widget extends State<GeneratedQ9Widget> {

  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
          opacity: 0.800000011920929,
          child: ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              width: 385.0,
              height: 800.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 241, 241, 243),
                      ),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 67.0,
                      height: 34.0,
                      child: TransformHelper.translate(
                          x: -124.00,
                          y: -344.00,
                          z: 0,
                          child: GeneratedBackbuttonWidget8()),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 297.0,
                      height: 50.0,
                      child: TransformHelper.translate(
                          x: -1.00,
                          y: -265.00,
                          z: 0,
                          child: Generated99WasteConsciousWidget()),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 297.0,
                      height: 59.0,
                      child: TransformHelper.translate(
                          x: -1.00,
                          y: -201.50,
                          z: 0,
                          child:
                          GeneratedHowmanymealsperweekdoyoueatmeatorfishWidget()),
                    ),

                    //0 meals
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 51.0,
                      child: TransformHelper.translate(
                          x: 1.00,
                          y: -89.50,
                          z: 0,
                          child: TextButton(
                            onPressed: () {
                              int value = 20;
                            },
                            child: Text('0 meals',
                                style: TextStyle(
                                    color:Colors.black
                                )),
                            style: ButtonStyle(
                                backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                            ),
                          ))
                    ),


                    //1-3 meals
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 51.0,
                      child: TransformHelper.translate(
                          x: 1.00,
                          y: -25.50,
                          z: 0,
                          child: TextButton(
                            onPressed: () {
                              int value = 10;
                            },
                            child: Text('1-3 meals',
                                style: TextStyle(
                                    color:Colors.black
                                )),
                            style: ButtonStyle(
                                backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                            ),
                          ))
                    ),


                    //4-6 meals
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 51.0,
                      child: TransformHelper.translate(
                          x: 1.00,
                          y: 38.50,
                          z: 0,
                          child: TextButton(
                            onPressed: () {
                              int value = 20;
                            },
                            child: Text('4-6 meals',
                                style: TextStyle(
                                    color:Colors.black
                                )),
                            style: ButtonStyle(
                                backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                            ),
                          ))
                    ),

                    //7-10 meals
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 51.0,
                      child: TransformHelper.translate(
                          x: 0.00,
                          y: 102.50,
                          z: 0,
                          child: TextButton(
                            onPressed: () {
                              int value = 35;
                            },
                            child: Text('7-10 meals',
                                style: TextStyle(
                                    color:Colors.black
                                )),
                            style: ButtonStyle(
                                backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                            ),
                          ))
                    ),

                    //10 meals
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 51.0,
                      child: TransformHelper.translate(
                          x: 0.00,
                          y: 166.50,
                          z: 0,
                          child: TextButton(
                            onPressed: () {
                              int value = 50;
                            },
                            child: Text('10 meals',
                                style: TextStyle(
                                    color:Colors.black
                                )),
                            style: ButtonStyle(
                                backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                            ),
                          ))
                    ),

                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 57.0,
                      child: TransformHelper.translate(
                          x: 1.00,
                          y: 289.50,
                          z: 0,
                          child: GeneratedComponent4Widget7()),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 57.0,
                      child: TransformHelper.translate(
                          x: 1.00,
                          y: 289.50,
                          z: 0,
                          child: GeneratedComponent5Widget6()),
                    )
                  ]),
            ),
          ),
        ));
  }

}
