import 'package:flutter/material.dart';
import 'package:flutterapp/eco_trackapp/generatedquizpagewidget/generated/GeneratedComponent4Widget.dart';
import 'package:flutterapp/eco_trackapp/generatedquizpagewidget/generated/GeneratedQuizpageiconWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/eco_trackapp/generatedquizpagewidget/generated/GeneratedWerealwayschangingourhabitsFeelfreetoupdateyourquizresu.dart';
import 'package:flutterapp/eco_trackapp/generatedquizpagewidget/generated/GeneratedAndroidBrowserFrameWidget8.dart';
import 'package:flutterapp/eco_trackapp/generatedquizpagewidget/generated/GeneratedNavigationbarWidget3.dart';

/* Frame quiz page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQuizpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.800000011920929,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 385.0,
          height: 800.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 241, 241, 243),
                  ),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 298.0,
                  height: 122.0,
                  child: TransformHelper.translate(
                      x: 1.50,
                      y: -245.00,
                      z: 0,
                      child:
                          GeneratedWerealwayschangingourhabitsFeelfreetoupdateyourquizresu()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 385.0,
                  height: 54.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 373.00,
                      z: 0,
                      child: GeneratedNavigationbarWidget3()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 278.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 0.50,
                      y: 191.50,
                      z: 0,
                      child: GeneratedComponent4Widget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 292.0,
                  height: 279.0,
                  child: TransformHelper.translate(
                      x: -1.50,
                      y: -35.50,
                      z: 0,
                      child: GeneratedQuizpageiconWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 324.0,
                  height: 26.0,
                  child: TransformHelper.translate(
                      x: 0.50,
                      y: -371.00,
                      z: 0,
                      child: GeneratedAndroidBrowserFrameWidget8()),
                )
              ]),
        ),
      ),
    ));
  }
}
