import 'package:flutter/material.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedHabit1iconWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedHabit2iconWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedCheckmarkWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedCarpoolinsteadofdriveWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedWalkinsteadofdriveWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedVector1Widget.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedHabit8iconWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedCheckmarkWidget2.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedHaveameatlessmealWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedVector2Widget.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedRecycleorreuseWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedCompostfoodscrapsWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedItsanewdayDidyoucompleteanyofthefollowingWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedCheckmarkWidget3.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedAndroidBrowserFrameWidget6.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedCheckmarkWidget1.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedHabit6iconWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedCheckmarkWidget4.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedRectangle15Widget6.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedHabit7iconWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/eco_trackapp/generatedhomepagewidget/generated/GeneratedNavigationbarWidget2.dart';

/* Frame home page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomepageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.800000011920929,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Container(
                width: 385.0,
                height: 800.0,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    overflow: Overflow.visible,
                    children: [
                      ClipRRect(
                        borderRadius: BorderRadius.zero,
                        child: Container(
                          color: Color.fromARGB(255, 241, 241, 243),
                        ),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 294.0,
                        height: 76.0,
                        child: TransformHelper.translate(
                            x: -1.50,
                            y: -261.00,
                            z: 0,
                            child:
                                GeneratedItsanewdayDidyoucompleteanyofthefollowingWidget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 295.0,
                        height: 70.0,
                        child: TransformHelper.translate(
                            x: 0.00,
                            y: -175.00,
                            z: 0,
                            child: GeneratedRectangle11Widget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 20.0,
                        height: 21.0,
                        child: TransformHelper.translate(
                            x: 123.50,
                            y: -175.50,
                            z: 0,
                            child: GeneratedCheckmarkWidget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 15.0,
                        height: 12.0,
                        child: TransformHelper.translate(
                            x: 123.00,
                            y: -176.00,
                            z: 0,
                            child: GeneratedVector1Widget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 324.0,
                        height: 26.0,
                        child: TransformHelper.translate(
                            x: 0.50,
                            y: -351.00,
                            z: 0,
                            child: GeneratedAndroidBrowserFrameWidget6()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 162.0,
                        height: 44.0,
                        child: TransformHelper.translate(
                            x: 21.50,
                            y: -174.00,
                            z: 0,
                            child: GeneratedHaveameatlessmealWidget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 295.0,
                        height: 70.0,
                        child: TransformHelper.translate(
                            x: 0.00,
                            y: -71.00,
                            z: 0,
                            child: GeneratedRectangle12Widget1()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 20.0,
                        height: 21.0,
                        child: TransformHelper.translate(
                            x: 123.50,
                            y: -71.50,
                            z: 0,
                            child: GeneratedCheckmarkWidget1()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 162.0,
                        height: 44.0,
                        child: TransformHelper.translate(
                            x: 21.50,
                            y: -70.00,
                            z: 0,
                            child: GeneratedRecycleorreuseWidget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 295.0,
                        height: 70.0,
                        child: TransformHelper.translate(
                            x: 0.00,
                            y: 32.00,
                            z: 0,
                            child: GeneratedRectangle13Widget1()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 20.0,
                        height: 21.0,
                        child: TransformHelper.translate(
                            x: 123.50,
                            y: 31.50,
                            z: 0,
                            child: GeneratedCheckmarkWidget2()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 162.0,
                        height: 44.0,
                        child: TransformHelper.translate(
                            x: 21.50,
                            y: 33.00,
                            z: 0,
                            child: GeneratedCompostfoodscrapsWidget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 80.0,
                        height: 80.0,
                        child: TransformHelper.translate(
                            x: -101.50,
                            y: -175.00,
                            z: 0,
                            child: GeneratedHabit6iconWidget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 80.0,
                        height: 53.33333206176758,
                        child: TransformHelper.translate(
                            x: -101.50,
                            y: -76.33,
                            z: 0,
                            child: GeneratedHabit7iconWidget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 60.0,
                        height: 60.0,
                        child: TransformHelper.translate(
                            x: -102.50,
                            y: 30.00,
                            z: 0,
                            child: GeneratedHabit8iconWidget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 295.0,
                        height: 70.0,
                        child: TransformHelper.translate(
                            x: -4.00,
                            y: 135.00,
                            z: 0,
                            child: GeneratedRectangle14Widget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 20.0,
                        height: 21.0,
                        child: TransformHelper.translate(
                            x: 119.50,
                            y: 134.50,
                            z: 0,
                            child: GeneratedCheckmarkWidget3()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 15.0,
                        height: 12.0,
                        child: TransformHelper.translate(
                            x: 119.00,
                            y: 134.00,
                            z: 0,
                            child: GeneratedVector2Widget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 162.0,
                        height: 44.0,
                        child: TransformHelper.translate(
                            x: 17.50,
                            y: 136.00,
                            z: 0,
                            child: GeneratedCarpoolinsteadofdriveWidget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 80.0,
                        height: 80.0,
                        child: TransformHelper.translate(
                            x: -104.50,
                            y: 133.00,
                            z: 0,
                            child: GeneratedHabit1iconWidget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 295.0,
                        height: 70.0,
                        child: TransformHelper.translate(
                            x: -6.00,
                            y: 238.00,
                            z: 0,
                            child: GeneratedRectangle15Widget6()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 20.0,
                        height: 21.0,
                        child: TransformHelper.translate(
                            x: 117.50,
                            y: 237.50,
                            z: 0,
                            child: GeneratedCheckmarkWidget4()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 162.0,
                        height: 44.0,
                        child: TransformHelper.translate(
                            x: 15.50,
                            y: 239.00,
                            z: 0,
                            child: GeneratedWalkinsteadofdriveWidget()),
                      ),
                      Positioned(
                        left: null,
                        top: null,
                        right: null,
                        bottom: null,
                        width: 80.0,
                        height: 80.0,
                        child: TransformHelper.translate(
                            x: -101.50,
                            y: 232.00,
                            z: 0,
                            child: GeneratedHabit2iconWidget()),
                      )
                    ]),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 415.0,
                height: 54.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 315.00,
                    z: 0,
                    child: GeneratedNavigationbarWidget2()),
              )
            ]),
      ),
    ));
  }
}
