import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/eco_trackapp/generatedq8widget/generated/GeneratedComponent5Widget5.dart';
import 'package:flutterapp/eco_trackapp/generatedq8widget/generated/GeneratedRectangle10Widget6.dart';
import 'package:flutterapp/eco_trackapp/generatedq8widget/generated/GeneratedRarelyWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq8widget/generated/GeneratedSometimesWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq8widget/generated/GeneratedComponent4Widget6.dart';
import 'package:flutterapp/eco_trackapp/generatedq8widget/generated/Generated89WasteConsciousWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq8widget/generated/GeneratedRectangle8Widget6.dart';
import 'package:flutterapp/eco_trackapp/generatedq8widget/generated/GeneratedBackbuttonWidget7.dart';
import 'package:flutterapp/eco_trackapp/generatedq8widget/generated/GeneratedRectangle9Widget5.dart';
import 'package:flutterapp/eco_trackapp/generatedq8widget/generated/GeneratedRectangle7Widget6.dart';
import 'package:flutterapp/eco_trackapp/generatedq8widget/generated/GeneratedNeverWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq8widget/generated/GeneratedDoesyourhouseholdcompostWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq8widget/generated/GeneratedAlwaysWidget.dart';

/* Frame q8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQ8Widget extends StatefulWidget {
  @override
  _GeneratedQ8WidgetState createState() => _GeneratedQ8WidgetState();
}
class _GeneratedQ8WidgetState extends State<GeneratedQ8Widget> {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
          opacity: 0.800000011920929,
          child: ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              width: 385.0,
              height: 800.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 241, 241, 243),
                      ),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 67.0,
                      height: 34.0,
                      child: TransformHelper.translate(
                          x: -124.00,
                          y: -344.00,
                          z: 0,
                          child: GeneratedBackbuttonWidget7()),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 57.0,
                      child: TransformHelper.translate(
                          x: 1.00,
                          y: 289.50,
                          z: 0,
                          child: GeneratedComponent4Widget6()),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 57.0,
                      child: TransformHelper.translate(
                          x: 1.00,
                          y: 289.50,
                          z: 0,
                          child: GeneratedComponent5Widget5()),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 297.0,
                      height: 50.0,
                      child: TransformHelper.translate(
                          x: -1.00,
                          y: -265.00,
                          z: 0,
                          child: Generated89WasteConsciousWidget()),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 297.0,
                      height: 59.0,
                      child: TransformHelper.translate(
                          x: -1.00,
                          y: -201.50,
                          z: 0,
                          child: GeneratedDoesyourhouseholdcompostWidget()),
                    ),

                    // Always btn
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 51.0,
                      child: TransformHelper.translate(
                          x: 1.00,
                          y: -89.50,
                          z: 0,
                          child: TextButton(
                            onPressed: () {
                              int value = 0;
                            },
                            child: Text('Always',
                              style: TextStyle(
                                color: Colors.black,
                                height: 1.171875,
                                fontSize: 18.0,
                                fontFamily: 'Forum',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                            style: ButtonStyle(
                              backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                            ),
                          )),
                    ),

                    // Sometimes btn
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 51.0,
                      child: TransformHelper.translate(
                          x: 1.00,
                          y: -25.50,
                          z: 0,
                          child: TextButton(
                            onPressed: () {
                              int value = 10;
                            },
                            child: Text('Sometimes',
                              style: TextStyle(
                                color: Colors.black,
                                height: 1.171875,
                                fontSize: 18.0,
                                fontFamily: 'Forum',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                            style: ButtonStyle(
                              backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                            ),
                          )),
                    ),

                    // Rarely btn
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 51.0,
                      child: TransformHelper.translate(
                          x: 1.00,
                          y: 38.50,
                          z: 0,
                          child: TextButton(
                            onPressed: () {
                              int value = 15;
                            },
                            child: Text('Rarely',
                              style: TextStyle(
                                color: Colors.black,
                                height: 1.171875,
                                fontSize: 18.0,
                                fontFamily: 'Forum',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                            style: ButtonStyle(
                              backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                            ),
                          )),
                    ),

                    // Never btn
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 51.0,
                      child: TransformHelper.translate(
                          x: 0.00,
                          y: 102.50,
                          z: 0,
                          child: TextButton(
                            onPressed: () {
                              int value = 20;
                            },
                            child: Text('Never',
                              style: TextStyle(
                                color: Colors.black,
                                height: 1.171875,
                                fontSize: 18.0,
                                fontFamily: 'Forum',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                            style: ButtonStyle(
                              backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                            ),
                          )),
                    ),
                  ]),
            ),
          ),
        ));
  }
}