import 'package:flutter/material.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedRectangle10Widget2.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedRectangle7Widget2.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/Generated49MinimalistLivingWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedNaturalgasWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedRectangle8Widget2.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedElectricityWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedRectangle9Widget2.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedHowisyourhouseheatedWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedRenewableenergyWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedBackbuttonWidget3.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedOilWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedComponent4Widget2.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedComponent5Widget1.dart';

/* Frame q4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQ4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.800000011920929,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 385.0,
          height: 800.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 241, 241, 243),
                  ),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 67.0,
                  height: 34.0,
                  child: TransformHelper.translate(
                      x: -124.00,
                      y: -344.00,
                      z: 0,
                      child: GeneratedBackbuttonWidget3()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 50.0,
                  child: TransformHelper.translate(
                      x: -1.00,
                      y: -265.00,
                      z: 0,
                      child: Generated49MinimalistLivingWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 59.0,
                  child: TransformHelper.translate(
                      x: -1.00,
                      y: -201.50,
                      z: 0,
                      child: GeneratedHowisyourhouseheatedWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -89.50,
                      z: 0,
                      child: GeneratedRectangle7Widget2()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 277.0,
                  height: 35.0,
                  child: TransformHelper.translate(
                      x: 2.00,
                      y: -87.50,
                      z: 0,
                      child: GeneratedNaturalgasWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -25.50,
                      z: 0,
                      child: GeneratedRectangle8Widget2()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 280.0,
                  height: 38.0,
                  child: TransformHelper.translate(
                      x: 3.50,
                      y: -22.00,
                      z: 0,
                      child: GeneratedElectricityWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 38.50,
                      z: 0,
                      child: GeneratedRectangle9Widget2()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 280.0,
                  height: 38.0,
                  child: TransformHelper.translate(
                      x: 3.50, y: 42.00, z: 0, child: GeneratedOilWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 102.50,
                      z: 0,
                      child: GeneratedRectangle10Widget2()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 277.0,
                  height: 35.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 104.50,
                      z: 0,
                      child: GeneratedRenewableenergyWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 289.50,
                      z: 0,
                      child: GeneratedComponent4Widget2()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 289.50,
                      z: 0,
                      child: GeneratedComponent5Widget1()),
                )
              ]),
        ),
      ),
    ));
  }
}
