import 'package:flutter/material.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedRectangle10Widget2.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedRectangle7Widget2.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/Generated49MinimalistLivingWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedNaturalgasWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedRectangle8Widget2.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedElectricityWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedRectangle9Widget2.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedHowisyourhouseheatedWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedRenewableenergyWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedBackbuttonWidget3.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedOilWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedComponent4Widget2.dart';
import 'package:flutterapp/eco_trackapp/generatedq4widget/generated/GeneratedComponent5Widget1.dart';

/* Frame q4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQ4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.800000011920929,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 385.0,
          height: 800.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 241, 241, 243),
                  ),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 67.0,
                  height: 34.0,
                  child: TransformHelper.translate(
                      x: -124.00,
                      y: -295.00,
                      z: 0,
                      child: GeneratedBackbuttonWidget3()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 50.0,
                  child: TransformHelper.translate(
                      x: -1.00,
                      y: -250.00,
                      z: 0,
                      child: Generated49MinimalistLivingWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 59.0,
                  child: TransformHelper.translate(
                      x: -1.00,
                      y: -201.50,
                      z: 0,
                      child: GeneratedHowisyourhouseheatedWidget()),
                ),

                // Natural gas btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -89.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 30;
                        },
                        child: Text('Natural gas',
                          style: TextStyle(
                            color: Colors.black,
                            height: 1.171875,
                            fontSize: 18.0,
                            fontFamily: 'Forum',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                        style: ButtonStyle(
                          backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                        ),
                      )),
                ),

                // Electricity btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -25.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 40;
                        },
                        child: Text('Electricity',
                          style: TextStyle(
                            color: Colors.black,
                            height: 1.171875,
                            fontSize: 18.0,
                            fontFamily: 'Forum',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                        style: ButtonStyle(
                          backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                        ),
                      )),
                ),

                // Oil btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 38.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 50;
                        },
                        child: Text('Oil',
                          style: TextStyle(
                            color: Colors.black,
                            height: 1.171875,
                            fontSize: 18.0,
                            fontFamily: 'Forum',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                        style: ButtonStyle(
                          backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                        ),
                      )),
                ),

                // Renewable energy btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 102.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 10;
                        },
                        child: Text('Renewable energy',
                          style: TextStyle(
                            color: Colors.black,
                            height: 1.171875,
                            fontSize: 18.0,
                            fontFamily: 'Forum',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                        style: ButtonStyle(
                          backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                        ),
                      )),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 289.50,
                      z: 0,
                      child: GeneratedComponent4Widget2()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 289.50,
                      z: 0,
                      child: GeneratedComponent5Widget1()),
                )
              ]),
        ),
      ),
    ));
  }
}
