import 'package:flutter/material.dart';
import 'package:flutterapp/eco_trackapp/generatedq6widget/generated/GeneratedWhattypeofhomedoyouliveinWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq6widget/generated/Generated69MinimalistLivingWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq6widget/generated/GeneratedTrailerWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq6widget/generated/GeneratedRectangle10Widget5.dart';
import 'package:flutterapp/eco_trackapp/generatedq6widget/generated/GeneratedSemiDetachedWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq6widget/generated/GeneratedComponent4Widget5.dart';
import 'package:flutterapp/eco_trackapp/generatedq6widget/generated/GeneratedBackbuttonWidget6.dart';
import 'package:flutterapp/eco_trackapp/generatedq6widget/generated/GeneratedRectangle7Widget5.dart';
import 'package:flutterapp/eco_trackapp/generatedq6widget/generated/GeneratedRectangle9Widget4.dart';
import 'package:flutterapp/eco_trackapp/generatedq6widget/generated/GeneratedApartmentWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq6widget/generated/GeneratedDetachedWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq6widget/generated/GeneratedRectangle8Widget5.dart';
import 'package:flutterapp/eco_trackapp/generatedq6widget/generated/GeneratedComponent5Widget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame q6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQ6Widget extends StatefulWidget {
  @override
  _GeneratedQ6WidgetState createState() => _GeneratedQ6WidgetState();
}
class _GeneratedQ6WidgetState extends State<GeneratedQ6Widget> {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
          opacity: 0.800000011920929,
          child: ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              width: 385.0,
              height: 800.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 241, 241, 243),
                      ),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 67.0,
                      height: 34.0,
                      child: TransformHelper.translate(
                          x: -124.00,
                          y: -295.00,
                          z: 0,
                          child: GeneratedBackbuttonWidget6()),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 297.0,
                      height: 50.0,
                      child: TransformHelper.translate(
                          x: -1.00,
                          y: -250.00,
                          z: 0,
                          child: Generated69MinimalistLivingWidget()),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 297.0,
                      height: 59.0,
                      child: TransformHelper.translate(
                          x: -1.00,
                          y: -201.50,
                          z: 0,
                          child: GeneratedWhattypeofhomedoyouliveinWidget()),
                    ),

                    // Apartment btn
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 51.0,
                      child: TransformHelper.translate(
                          x: 1.00,
                          y: -89.50,
                          z: 0,
                          child: TextButton(
                            onPressed: () {
                              int value = 20;
                            },
                            child: Text('Apartment',
                              style: TextStyle(
                                color: Colors.black,
                                height: 1.171875,
                                fontSize: 18.0,
                                fontFamily: 'Forum',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                            style: ButtonStyle(
                              backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                            ),
                          )),
                    ),

                    // Detached btn
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 51.0,
                      child: TransformHelper.translate(
                          x: 1.00,
                          y: -25.50,
                          z: 0,
                          child: TextButton(
                            onPressed: () {
                              // int value = 0;
                            },
                            child: Text('Detached',
                              style: TextStyle(
                                color: Colors.black,
                                height: 1.171875,
                                fontSize: 18.0,
                                fontFamily: 'Forum',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                            style: ButtonStyle(
                              backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                            ),
                          )),
                    ),

                    // Trailer btn
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 280.0,
                      height: 38.0,
                      child: TransformHelper.translate(
                          x: 1.00,
                          y: 38.50,
                          z: 0,
                          child: TextButton(
                            onPressed: () {
                              // int value = 0;
                            },
                            child: Text('Trailer',
                              style: TextStyle(
                                color: Colors.black,
                                height: 1.171875,
                                fontSize: 18.0,
                                fontFamily: 'Forum',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                            style: ButtonStyle(
                              backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                            ),
                          )),
                    ),

                    // House btn
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 51.0,
                      child: TransformHelper.translate(
                          x: 0.00,
                          y: 102.50,
                          z: 0,
                          child: TextButton(
                            onPressed: () {
                              // int value = 0;
                            },
                            child: Text('House',
                              style: TextStyle(
                                color: Colors.black,
                                height: 1.171875,
                                fontSize: 18.0,
                                fontFamily: 'Forum',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                            style: ButtonStyle(
                              backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                            ),
                          )),
                    ),

                    // Semi-detached btn
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 51.0,
                      child: TransformHelper.translate(
                          x: 0.00,
                          y: 166.50,
                          z: 0,
                          child: TextButton(
                            onPressed: () {
                              // int value = 0;
                            },
                            child: Text('Semi-detached',
                              style: TextStyle(
                                color: Colors.black,
                                height: 1.171875,
                                fontSize: 18.0,
                                fontFamily: 'Forum',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                            style: ButtonStyle(
                              backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229)),
                            ),
                          )),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 57.0,
                      child: TransformHelper.translate(
                          x: 1.00,
                          y: 289.50,
                          z: 0,
                          child: GeneratedComponent4Widget5()),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 57.0,
                      child: TransformHelper.translate(
                          x: 1.00,
                          y: 289.50,
                          z: 0,
                          child: GeneratedComponent5Widget4()),
                    ),

                  ]),
            ),
          ),
        ));
  }
}