import 'package:flutter/material.dart';
import 'package:flutterapp/eco_trackapp/generatedq5widget/generated/GeneratedBackbuttonWidget5.dart';
import 'package:flutterapp/eco_trackapp/generatedq5widget/generated/GeneratedRectangle8Widget4.dart';
import 'package:flutterapp/eco_trackapp/generatedq5widget/generated/Generated23peopleWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq5widget/generated/Generated59MinimalistLivingWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq5widget/generated/GeneratedRectangle11Widget3.dart';
import 'package:flutterapp/eco_trackapp/generatedq5widget/generated/GeneratedRectangle10Widget4.dart';
import 'package:flutterapp/eco_trackapp/generatedq5widget/generated/Generated1personWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq5widget/generated/Generated5peopleWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq5widget/generated/Generated45peopleWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq5widget/generated/GeneratedComponent4Widget4.dart';
import 'package:flutterapp/eco_trackapp/generatedq5widget/generated/GeneratedRectangle7Widget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/eco_trackapp/generatedq5widget/generated/GeneratedComponent5Widget3.dart';
import 'package:flutterapp/eco_trackapp/generatedq5widget/generated/GeneratedHowmanypeopleliveinyourhouseholdWidget.dart';

/* Frame q5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQ5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.800000011920929,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 385.0,
          height: 800.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 241, 241, 243),
                  ),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 67.0,
                  height: 34.0,
                  child: TransformHelper.translate(
                      x: -124.00,
                      y: -344.00,
                      z: 0,
                      child: GeneratedBackbuttonWidget5()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 50.0,
                  child: TransformHelper.translate(
                      x: -1.00,
                      y: -265.00,
                      z: 0,
                      child: Generated59MinimalistLivingWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 59.0,
                  child: TransformHelper.translate(
                      x: -1.00,
                      y: -201.50,
                      z: 0,
                      child: GeneratedHowmanypeopleliveinyourhouseholdWidget()),
                ),

                //1 person
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -89.50,
                      z: 0,
                      child: TextButton(
                      onPressed: () {
                int value = 0;
                },
                  child: Text('1 person',
                      style: TextStyle(
                          color:Colors.black
                      )),
                  style: ButtonStyle(
                      backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                  ),
                ))
      ),


                //2-3ppl
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -25.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 0;
                        },
                        child: Text('2-3 people',
                            style: TextStyle(
                                color:Colors.black
                            )),
                        style: ButtonStyle(
                            backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                        ),
                      ))
                ),


                //4-5 ppl
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 38.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 0;
                        },
                        child: Text('4-5 people',
                            style: TextStyle(
                                color:Colors.black
                            )),
                        style: ButtonStyle(
                            backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                        ),
                      ))
                ),


                //5 ppl
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 102.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 0;
                        },
                        child: Text('5 people',
                            style: TextStyle(
                                color:Colors.black
                            )),
                        style: ButtonStyle(
                            backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                        ),
                      ))
                ),

                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 289.50,
                      z: 0,
                      child: GeneratedComponent4Widget4()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 289.50,
                      z: 0,
                      child: GeneratedComponent5Widget3()),
                )
              ]),
        ),
      ),
    ));
  }
}
