import 'package:flutter/material.dart';
import 'package:flutterapp/eco_trackapp/generatedquizresultswidget/generated/GeneratedButtheresroomforimprovementtooHitcompletetoviewyourpers.dart';
import 'package:flutterapp/eco_trackapp/generatedquizresultswidget/generated/GeneratedAndroidBrowserFrameWidget2.dart';
import 'package:flutterapp/eco_trackapp/generatedquizresultswidget/generated/GeneratedComponent6Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/eco_trackapp/generatedquizresultswidget/generated/GeneratedWoohooYourewhatwecallacleantravellerWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedquizresultswidget/generated/GeneratedFabuloustrip11Widget.dart';

/* Frame quiz results
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQuizresultsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.800000011920929,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 385.0,
          height: 800.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 241, 241, 243),
                  ),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 192.0,
                  height: 184.0,
                  child: TransformHelper.translate(
                      x: 0.50,
                      y: -159.00,
                      z: 0,
                      child: GeneratedFabuloustrip11Widget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 257.0,
                  height: 76.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -287.00,
                      z: 0,
                      child:
                          GeneratedWoohooYourewhatwecallacleantravellerWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 257.0,
                  height: 76.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 7.00,
                      z: 0,
                      child:
                          GeneratedButtheresroomforimprovementtooHitcompletetoviewyourpers()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 324.0,
                  height: 26.0,
                  child: TransformHelper.translate(
                      x: 0.50,
                      y: -374.00,
                      z: 0,
                      child: GeneratedAndroidBrowserFrameWidget2()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: -2.00,
                      y: 301.50,
                      z: 0,
                      child: GeneratedComponent6Widget1()),
                )
              ]),
        ),
      ),
    ));
  }
}
