import 'package:flutter/material.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedComponent4Widget3.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedWalkWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedBackbuttonWidget4.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedRectangle8Widget3.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedRectangle11Widget2.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/Generated39CleanTravellerWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedCarpoolWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedComponent5Widget2.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedCarWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedHowdoyougettoschoolworkWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedPublictransportSchoolBusWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedRectangle10Widget3.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedRectangle7Widget3.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedBicyclerollerbladeskateboardWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedRectangle9Widget3.dart';

/* Frame q3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQ3Widget extends StatefulWidget {
  @override
  _GeneratedQ3WidgetState createState() => _GeneratedQ3WidgetState();
}
class _GeneratedQ3WidgetState extends State<GeneratedQ3Widget> {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.800000011920929,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 385.0,
          height: 800.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 241, 241, 243),
                  ),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 67.0,
                  height: 34.0,
                  child: TransformHelper.translate(
                      x: -124.00,
                      y: -295.00,
                      z: 0,
                      child: GeneratedBackbuttonWidget4()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 50.0,
                  child: TransformHelper.translate(
                      x: -1.00,
                      y: -250.00,
                      z: 0,
                      child: Generated39CleanTravellerWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 59.0,
                  child: TransformHelper.translate(
                      x: -1.00,
                      y: -201.50,
                      z: 0,
                      child: GeneratedHowdoyougettoschoolworkWidget()),
                ),

                // Car btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -89.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 50;
                        },
                        child: Text('Car',
                            style: TextStyle(
                                color:Colors.black
                            )),
                        style: ButtonStyle(
                            backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                        ),
                      ))
                ),


                // Public transport btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -25.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 25;
                        },
                        child: Text('Public Transport',
                            style: TextStyle(
                                color:Colors.black
                            )),
                        style: ButtonStyle(
                            backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                        ),
                      ))
                ),


                // Carpool btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 38.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 20;
                        },
                        child: Text('Carpool',
                            style: TextStyle(
                                color:Colors.black
                            )),
                        style: ButtonStyle(
                            backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                        ),
                      ))
                ),


                // Walk btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 102.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 0;
                        },
                        child: Text('Walk',
                            style: TextStyle(
                                color:Colors.black
                            )),
                        style: ButtonStyle(
                            backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                        ),
                      ))
                ),


                // Bicycle/rollerblade/skateboard btn
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 166.50,
                      z: 0,
                      child: TextButton(
                        onPressed: () {
                          int value = 0;
                        },
                        child: Text('Bicycle / rollerblade / skateboard',
                            style: TextStyle(
                                color:Colors.black
                            )),
                        style: ButtonStyle(
                            backgroundColor: MaterialStateProperty.all<Color>(Color.fromARGB(255, 229, 229, 229))
                        ),
                      ))
                ),

                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 289.50,
                      z: 0,
                      child: GeneratedComponent4Widget3()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 289.50,
                      z: 0,
                      child: GeneratedComponent5Widget2()),
                )
              ]),
        ),
      ),
    ));
  }
}
