import 'package:flutter/material.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedComponent4Widget3.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedWalkWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedBackbuttonWidget4.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedRectangle8Widget3.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedRectangle11Widget2.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/Generated39CleanTravellerWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedCarpoolWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedComponent5Widget2.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedCarWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedHowdoyougettoschoolworkWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedPublictransportSchoolBusWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedRectangle10Widget3.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedRectangle7Widget3.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedBicyclerollerbladeskateboardWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedq3widget/generated/GeneratedRectangle9Widget3.dart';

/* Frame q3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQ3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.800000011920929,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 385.0,
          height: 800.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 241, 241, 243),
                  ),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 67.0,
                  height: 34.0,
                  child: TransformHelper.translate(
                      x: -124.00,
                      y: -344.00,
                      z: 0,
                      child: GeneratedBackbuttonWidget4()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 50.0,
                  child: TransformHelper.translate(
                      x: -1.00,
                      y: -265.00,
                      z: 0,
                      child: Generated39CleanTravellerWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 59.0,
                  child: TransformHelper.translate(
                      x: -1.00,
                      y: -201.50,
                      z: 0,
                      child: GeneratedHowdoyougettoschoolworkWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -89.50,
                      z: 0,
                      child: GeneratedRectangle7Widget3()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 280.0,
                  height: 38.0,
                  child: TransformHelper.translate(
                      x: 3.50, y: -86.00, z: 0, child: GeneratedCarWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: -25.50,
                      z: 0,
                      child: GeneratedRectangle8Widget3()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 277.0,
                  height: 35.0,
                  child: TransformHelper.translate(
                      x: 2.00,
                      y: -23.50,
                      z: 0,
                      child: GeneratedPublictransportSchoolBusWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 38.50,
                      z: 0,
                      child: GeneratedRectangle9Widget3()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 280.0,
                  height: 38.0,
                  child: TransformHelper.translate(
                      x: 3.50, y: 42.00, z: 0, child: GeneratedCarpoolWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 102.50,
                      z: 0,
                      child: GeneratedRectangle10Widget3()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 280.0,
                  height: 38.0,
                  child: TransformHelper.translate(
                      x: 2.50, y: 106.00, z: 0, child: GeneratedWalkWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 166.50,
                      z: 0,
                      child: GeneratedRectangle11Widget2()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 277.0,
                  height: 35.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 168.50,
                      z: 0,
                      child: GeneratedBicyclerollerbladeskateboardWidget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 289.50,
                      z: 0,
                      child: GeneratedComponent4Widget3()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 57.0,
                  child: TransformHelper.translate(
                      x: 1.00,
                      y: 289.50,
                      z: 0,
                      child: GeneratedComponent5Widget2()),
                )
              ]),
        ),
      ),
    ));
  }
}
