import 'package:flutter/material.dart';
import 'package:flutterapp/eco_trackapp/generatedprogresspagewidget/generated/GeneratedComponent10Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/eco_trackapp/generatedprogresspagewidget/generated/GeneratedAndroidBrowserFrameWidget4.dart';
import 'package:flutterapp/eco_trackapp/generatedprogresspagewidget/generated/GeneratedTakethebusinsteadofdrivingWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedprogresspagewidget/generated/GeneratedTurnoffunusedlightsWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedprogresspagewidget/generated/GeneratedComponent12Widget.dart';
import 'package:flutterapp/eco_trackapp/generatedprogresspagewidget/generated/GeneratedThisisyourweeklyprogressWidget.dart';
import 'package:flutterapp/eco_trackapp/generatedprogresspagewidget/generated/GeneratedNavigationbarWidget1.dart';
import 'package:flutterapp/eco_trackapp/generatedprogresspagewidget/generated/GeneratedComponent8Widget.dart';
import 'package:flutterapp/eco_trackapp/generatedprogresspagewidget/generated/GeneratedOptoutofeatingredmeatWidget.dart';

/* Frame progress page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProgresspageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.800000011920929,
      child: GestureDetector(
        onTap: () =>
            Navigator.pushNamed(context, '/GeneratedProgressiconWidget1'),
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            width: 385.0,
            height: 800.0,
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,
                overflow: Overflow.visible,
                children: [
                  ClipRRect(
                    borderRadius: BorderRadius.zero,
                    child: Container(
                      color: Color.fromARGB(255, 241, 241, 243),
                    ),
                  ),
                  Positioned(
                    left: null,
                    top: null,
                    right: null,
                    bottom: null,
                    width: 295.0,
                    height: 70.0,
                    child: TransformHelper.translate(
                        x: 0.00,
                        y: -159.00,
                        z: 0,
                        child: GeneratedComponent8Widget()),
                  ),
                  Positioned(
                    left: null,
                    top: null,
                    right: null,
                    bottom: null,
                    width: 257.0,
                    height: 76.0,
                    child: TransformHelper.translate(
                        x: 1.00,
                        y: -276.00,
                        z: 0,
                        child: GeneratedThisisyourweeklyprogressWidget()),
                  ),
                  Positioned(
                    left: null,
                    top: null,
                    right: null,
                    bottom: null,
                    width: 277.0,
                    height: 35.0,
                    child: TransformHelper.translate(
                        x: 1.00,
                        y: -209.50,
                        z: 0,
                        child: GeneratedTakethebusinsteadofdrivingWidget()),
                  ),
                  Positioned(
                    left: null,
                    top: null,
                    right: null,
                    bottom: null,
                    width: 295.0,
                    height: 70.0,
                    child: TransformHelper.translate(
                        x: 0.00,
                        y: -22.00,
                        z: 0,
                        child: GeneratedComponent10Widget()),
                  ),
                  Positioned(
                    left: null,
                    top: null,
                    right: null,
                    bottom: null,
                    width: 277.0,
                    height: 35.0,
                    child: TransformHelper.translate(
                        x: 1.00,
                        y: -72.50,
                        z: 0,
                        child: GeneratedTurnoffunusedlightsWidget()),
                  ),
                  Positioned(
                    left: null,
                    top: null,
                    right: null,
                    bottom: null,
                    width: 295.0,
                    height: 70.0,
                    child: TransformHelper.translate(
                        x: 2.00,
                        y: 115.00,
                        z: 0,
                        child: GeneratedComponent12Widget()),
                  ),
                  Positioned(
                    left: null,
                    top: null,
                    right: null,
                    bottom: null,
                    width: 277.0,
                    height: 35.0,
                    child: TransformHelper.translate(
                        x: 3.00,
                        y: 64.50,
                        z: 0,
                        child: GeneratedOptoutofeatingredmeatWidget()),
                  ),
                  Positioned(
                    left: null,
                    top: null,
                    right: null,
                    bottom: null,
                    width: 385.0,
                    height: 54.0,
                    child: TransformHelper.translate(
                        x: 0.00,
                        y: 373.00,
                        z: 0,
                        child: GeneratedNavigationbarWidget1()),
                  ),
                  Positioned(
                    left: null,
                    top: null,
                    right: null,
                    bottom: null,
                    width: 324.0,
                    height: 26.0,
                    child: TransformHelper.translate(
                        x: 0.50,
                        y: -371.00,
                        z: 0,
                        child: GeneratedAndroidBrowserFrameWidget4()),
                  )
                ]),
          ),
        ),
      ),
    ));
  }
}
